version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
      nodejs: 10
  pre_build:
    commands:
      - dotnet clean
      - echo pre_build completed on 'data'
  build:
    commands:
      - echo Build completed on 'data'
      - dotnet restore
      - dotnet test
  post_build:
    commands:
      - echo Build completed on `date`
      - dotnet pack
      - cp target**/*.dll dotnet.dll
artifacts:
  files:
    - dotnet.dll