version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - dotnet clean
      - echo pre_build completed on 'data'
  build:
    commands:
      - echo Build completed on 'data'
      - dotnet restore
      - dotnet build
      - dotnet test
  post_build:
    commands:
      - echo Build completed on `date`
      - dotnet publish
      - cp target/*.war sample-java.war
artifacts:
  files:
    - sample-java.war